# Generated by Django 5.2.5 on 2025-09-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verification_enabled', models.BooleanField(default=True)),
                ('phone_verification_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Verification Settings',
                'verbose_name_plural': 'Verification Settings',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
